package engineering.model;
// Generated Nov 1, 2023, 10:50:55 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "COURSE")
public class Course implements java.io.Serializable {

	private long id;
	private String coursename;
	private Set<Student> students = new HashSet<Student>(0);

	public Course() {
	}

	public Course(long id) {
		this.id = id;
	}

	public Course(long id, String coursename, Set<Student> students) {
		this.id = id;
		this.coursename = coursename;
		this.students = students;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "COURSENAME")
	public String getCoursename() {
		return this.coursename;
	}

	public void setCoursename(String coursename) {
		this.coursename = coursename;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "student_course", joinColumns = {
			@JoinColumn(name = "course_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "student_id", nullable = false, updatable = false) })
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
