package engineering.model;
// Generated Nov 1, 2023, 10:50:55 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Family generated by hbm2java
 */
@Entity
@Table(name = "FAMILY")
public class Family implements java.io.Serializable {

	private int id;
	private String description;
	private Set<Person> persons = new HashSet<Person>(0);

	public Family() {
	}

	public Family(int id) {
		this.id = id;
	}

	public Family(int id, String description, Set<Person> persons) {
		this.id = id;
		this.description = description;
		this.persons = persons;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "family")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
