package engineering.model;
// Generated Nov 1, 2023, 10:50:55 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON")
public class Person implements java.io.Serializable {

	private String id;
	private Family family;
	private String firstname;
	private String lastname;
	private Set<Job> jobs = new HashSet<Job>(0);

	public Person() {
	}

	public Person(String id) {
		this.id = id;
	}

	public Person(String id, Family family, String firstname, String lastname, Set<Job> jobs) {
		this.id = id;
		this.family = family;
		this.firstname = firstname;
		this.lastname = lastname;
		this.jobs = jobs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FAMILY_ID")
	public Family getFamily() {
		return this.family;
	}

	public void setFamily(Family family) {
		this.family = family;
	}

	@Column(name = "FIRSTNAME")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PERSON_JOB", joinColumns = {
			@JoinColumn(name = "Person_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "jobList_ID", nullable = false, updatable = false) })
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

}
