package engineering.model;
// Generated Nov 1, 2023, 10:50:55 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Todo generated by hbm2java
 */
@Entity
@Table(name = "todo")
public class Todo implements java.io.Serializable {

	private long id;
	private String description;
	private String summary;

	public Todo() {
	}

	public Todo(long id) {
		this.id = id;
	}

	public Todo(long id, String description, String summary) {
		this.id = id;
		this.description = description;
		this.summary = summary;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SUMMARY")
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

}
